### ISSUE TITLE
Add support for non-Windows agents

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake-vso#14]
Right now only Windows agents are supported. We should add support for non-Windows agents as well.

**Comment by stefandevo** [comment]
Please Please Please !!!!

**Comment by JasonDonnelly** [comment]
Can you do macOS today please ;-)

**Comment by valdetero** [comment]
Just tried to run it on OSX for Xamarin builds which don't work. Would love for this to be implemented.

**Comment by Marusyk** [comment]
any news?

**Comment by valdetero** [comment]
@Marusyk I ended up just kicking it off via command-line.

I added a Command-Line task in my build definition in VSTS/TFS for ./build.sh and passed it these arguments: `--script mobile.cake --target=My-Target-To-Build-Mobile --configuration=$(BuildConfiguration)`

Make note that the arguments have different syntax (space vs. equals). This took hours to figure out. Also created a cake file for mobile only (mobile.cake vs the default build.cake).

I also had to put a command-line script before that that calls `chmod` with the arguments `-Rv 755 ./build.sh` since it could not execute the script when pulling the source code for the first time.

**Comment by sdebruyn** [comment]
Looks like we'd need a Node JS script that kicks off the bash script on MacOS and the PS script on Windows.

Example of a task that runs on Windows, Linux and macOS: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ArchiveFilesV2

**Comment by giggio** [comment]
Wouldn't this be pretty simple now that Cake has .NET Core support? All you need on the agent is the global tool installed.

**Comment by louisfischer** [comment]
This may also work. (I have only tried locally)

Requirements; 

1. Powershell Core is installed on Mac/Linux Hosted machine.
2. Add a Cake.sh to the task with the below code.
3. Modify the task.json to execute the Bash Script only on Linux or Mac

```bash
#!/bin/bash
pwsh ./build.ps1 "$@"
```

The "$@"  should maybe pass all the arguments from bash script to the powershell script

**Comment by johncrim** [comment]
I started investigating fixing this issue, and IMO it's not worth the effort to implement the fix (while maintaining backward compatibility), since the `dotnet-cake` tool makes it pretty easy to run cake builds on .NET Core on Linux build agents. Looking at the code for cake-vso, this task is really about bootstrapping Cake, then calling Cake, which is redundant with 'dotnet-cake' (I thought there might be some special output formatting for Azure DevOps, but that's not the case). While this build task certainly provides a nice UI for setting up a cake task, the YAML is pretty simple too.

IMO the "modern" way to use cake is to use `dotnet-cake` and skip checking the bootstrap scripts in (*.cake files only). Which means the build shouldn't require the bash or powershell bootstrap scripts.

Here's an [Azure Pipelines yaml file that runs a .NET Core cake build on Linux using `dotnet-cake`](https://gist.github.com/johncrim/b01b41fb8e6fe186539064a260fa9b81). I've tested it on Azure DevOps.

```
# Simple build pipeline for running Cake build on Ubuntu agent

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: DotNetCoreCLI@2
    displayName: Install dotnet Cake Build Tool
    inputs:
      command: custom
      custom: tool
      arguments: 'install -g Cake.Tool'

  - task: DotNetCoreCLI@2
    displayName: Cake Build
    inputs:
      command: custom
      custom: cake
      arguments: '--target=build --configuration=$(BuildConfiguration)'
```
